### PR TITLE
Make Uikit a node dependency; drop Submodule

### PR DESCRIPTION
**Pull request by felixheidecke**
Remove Uikit as a submodule and make it a node dependency

### CODE REVIEW

**Comment by felixheidecke** [comment]
# Todo:

- [ ] Remove all UIKit related tasks from Makefile
- [ ] Add `node_modules/less/bin/lessc src/themes/owncloud.less core/css/uikit.owncloud.css --relative-urls` to Makefile default process

**Comment by felixheidecke** [comment]
Nice. Works. I think we can merge this. Short review @DeepDiver1975 and/or @PVince81 ?!

**Comment by yaagee** [comment]
process_begin: CreateProcess(NULL, env node D:\doc\bbbbbb\phoenix\node_modules\less\bin\lessc src/themes/owncloud.less core/css/uikit.o
ls, ...) failed. how to fix this?

**Comment by felixheidecke** [comment]
Hmm … try `npm run build` as well as `node_modules/less/bin/lessc src/themes/owncloud.less core/css/uikit.owncloud.css --relative-urls` manually and see if that works for you.

**Pull request merged**
