### PR TITLE
Shared with me list

### PR DESCRIPTION
**Pull request by LukasHirt**
## Related Issue

- Refs #1186 

## How Has This Been Tested?

- test environment: Manually
1. Share file with user
2. Log in as that user
3. Navigate into Shared with me list
4. Accept pending share
5. Decline pending share
6. Accept pending share after declining it first

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Load also remote shares
- [ ] Write acceptance tests

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
- [ ] console error if there are no shared files
Screenshot from 2019-08-16 12-16-10
the code segment looks anyhow wrong - there is no current folder in this page from my perspective

**Comment by LukasHirt** [comment]
@DeepDiver1975 Thanks for discovering! Fixed now.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUILogin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4749/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUITrashbin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4752/

<p>
















</p></details>

**Pull request merged**
