### PR TITLE
WIP: Increase wait timeout in phoenix

### PR DESCRIPTION
**Pull request by skshetry**
Increasing timeout to check if it fails. If it doesnot, it's likely due to slowdown in drone.

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUINotifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5292/

<p>




</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRenameFolders</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5292/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFavorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5292/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5292/

<p>






</p></details>

**Comment by skshetry** [comment]
This should not be a  problem for now. If it happens again, please change the timeout as done in the PR. Awaiting trashbin deletion was merged in #2093 and webUILogin was made more reliable in #2109. Closing for now...

**Pull request closed without merging**
