### PR TITLE
Wait for ajax calls to finish before waiting for css property

### PR DESCRIPTION
**Pull request by skshetry**
## Description

The deletion popup takes a bit of time to disappear, after confirming for deletion.
We want to wait for the popup to disappear, and successful deletion of file in the server.

Also, we want to maximize time before the popup disappears. So, reversing the order of
wait provides us maximum waiting.

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by HariBhandari07** [comment]
LGTM

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6098/

<p>















</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6104/

<p>




















































</p></details>

**Comment by skshetry** [comment]
Closing as #2417 has been merged which has a workaround for this

**Pull request closed without merging**
