### PR TITLE
Allow overwrite in file upload in case the file already exists

### PR DESCRIPTION
**Pull request by DeepDiver1975**
##  Description
In case a file to be uploaded already exists we ask now the user if the file shall be overwritten

## ToDo
Implement a nice dialog instead of javascript confirm() -> done but needs review now

## Related Issue
- refs #1150 

## How Has This Been Tested?
- :hand: 

## Screenshots (if appropriate):
image
Screenshot from 2019-07-11 10-49-06

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by LukasHirt** [comment]
Nice

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUITrashbin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4018/10

<p>





</p></details>

**Comment by DeepDiver1975** [comment]
acceptance tests are now failing :see_no_evil:

**Comment by LukasHirt** [comment]
There were some merge conflicts - resolved now :wink:

**Pull request merged**
