### PR TITLE
Added trashbin

### LINKED ISSUE #273: Trashbin Support
Story:
Give a user is logged in
When the user opens 'deleted files' (UX to be defined)
Then deleted files are displayed with the information: name, old location, file size, file mtime, file icon and actions to restore and to permanent delete the file

Tasks:
- display trahsbin (1MD)
- add functions to js-owncloud-client to list the trahsbin (2MD)
- add public webdav api to allow access to the trashbin (including acceptance tests): https://github.com/owncloud/core/issues/15646 (4MD)

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Added trashbin into Phoenix

## Related Issue

- Fixes #273 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [x] Add clear function
- [x] Fix deletion timestamp
- [x] Add restore function
- [ ] Fix clear and restore of multiple selected files
- [x] Remove files from list after clear function
- [ ] Write acceptance tests
- [ ] Disable trash bin if server has no capability for it
- [ ] user feedback on restore and permanent delete

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3601/23

<p>















</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3603/24

<p>















</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3609/23

<p>















</p></details>

**Comment by LukasHirt** [comment]
@DeepDiver1975 Scenarios for failing delete and restore of multiple files:

**Delete**
Scenario:
1. Select multiple files
2. Delete them

Result:
One file is deleted and the second fails with error message "Error: 500 - files/(id of file) is locked"

**Restore**
Scenario:
1. Select multiple files
2. Restore them

Result:
One file is gone from the list and notification about its restoration is triggered but the second one triggers a fail notification without any description of error. In network in dev tools you can see the same error as in delete scenario. Strangely if you refresh, the file actually was restored.

**Comment by DeepDiver1975** [comment]
> **Delete**
> Scenario:
> 
>     1. Select multiple files
> 
>     2. Delete them
> 
> 
> Result:
> One file is deleted and the second fails with error message "Error: 500 - files/(id of file) is locked"

I cannot reproduce this one :see_no_evil:

**Comment by DeepDiver1975** [comment]
> **Restore**
> Scenario:
> 
>     1. Select multiple files
> 
>     2. Restore them
> 
> 
> Result:
> One file is gone from the list and notification about its restoration is triggered but the second one triggers a fail notification without any description of error. In network in dev tools you can see the same error as in delete scenario. Strangely if you refresh, the file actually was restored.

I'm also having a hard time to reproduce this. Let's blame your MacBook :rofl:

**Comment by LukasHirt** [comment]
> > **Restore**
> > Scenario:
> > ```
> > 1. Select multiple files
> > 
> > 2. Restore them
> > ```
> > 
> > 
> > Result:
> > One file is gone from the list and notification about its restoration is triggered but the second one triggers a fail notification without any description of error. In network in dev tools you can see the same error as in delete scenario. Strangely if you refresh, the file actually was restored.
> 
> I'm also having a hard time to reproduce this. Let's blame your MacBook 🤣

Could it then maybe happen because I’m running the server in docker and because of the different branch I’m creating the container from image in my local file system and everything is then damn slow in the container? And the call from api could be too fast repeated?

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUILogin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3663/6

<p>





</p></details>

**Comment by DeepDiver1975** [comment]
> Could it then maybe happen because I’m running the server in docker and because of the different branch I’m creating the container from image in my local file system and everything is then damn slow in the container? And the call from api could be too fast repeated?

yes - timing could just play badly into this ....

**Pull request merged**
