### PR TITLE
Switch OAuth/OpenId Connect library

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

OAuth2 config will look like:
```json
{
  "server": "http://localhost:8080",
  "theme": "owncloud",
  "version": "0.1.0",
  "auth": {
		"clientId": "Cxfj9F9ZZWQbQZps1E1M0BszMz6OOFq3lxjSuc8Uh4HLEYb9KIfyRMmgY5ibXXrU",
		"url": "http://localhost:8080/index.php/apps/oauth2/api/v1/token",
		"authUrl": "http://localhost:8080/index.php/apps/oauth2/authorize"
  },
  "apps" : [
    "files"
  ]
}
```

OpenId Connect:
```json
{
	"server" : "http://deepdiver:8080",
	"theme": "owncloud",
	"version": "0.1.0",
	"auth" : {
		"clientId": "Cxfj9F9ZZWQbQZps1E1M0BszMz6OOFq3lxjSuc8Uh4HLEYb9KIfyRMmgY5ibXXrU",
		"metaDataUrl": "https://owncloud.localhost:8443/.well-known/openid-configuration",
		"url": "https://owncloud.localhost:8443"
	},
	"apps" : [
		"files", "markdown-editor","pdf-viewer"
	]
}
```

The config requires some cleanup .....

This only replaces the used library. Implicit grant still used with OAuth when talking to ownCloud.
The OpenId Connect flow already uses Auth Code and refreshing the token works.

## Related Issue
- refs #511 

## How Has This Been Tested?
- :hand: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Add PKCE support
- [ ] Cleanup config settings in config.json

### CODE REVIEW

**Comment by scramb** [comment]
Got some issues login in... Is there anything i need to change in config?
2019-01-24-151821_942x964_scrot
2019-01-24-151736_951x126_scrot

**Comment by butonic** [comment]
hm auth.js takes `window.location.origin` as basis for the callback, but that will take kerio as the base url ... an my case `https://owncloud.localhost:8443/` but I need  `https://owncloud.localhost:8443/phoenix/` ... If I hardcode that it works fine.

**Comment by DeepDiver1975** [comment]
>  kerio

:question:

**Comment by DeepDiver1975** [comment]
> hm auth.js takes `window.location.origin` as basis for the callback, but that will take kerio as the base url ... an my case `https://owncloud.localhost:8443/` but I need `https://owncloud.localhost:8443/phoenix/` ... If I hardcode that it works fine.

Thx for testing - I'll have a look asap ...

**Comment by DeepDiver1975** [comment]
@butonic mind testing this commit? 76e57b89af52cc6fc5516751f4216e2b0b5a7001 - THX

**Comment by butonic** [comment]
@DeepDiver1975 hm, `window.location.pathname` may end in a `/`, leading to kopano connect crying about an invalid url again. 
```
diff --git a/src/services/auth.js b/src/services/auth.js
index 84f2cca..7b4a520 100644
--- a/src/services/auth.js
+++ b/src/services/auth.js
@@ -15,13 +15,13 @@ export function initVueAuthenticate (config) {
         // with OAuth2 we need to se the metadata manually
         metadataUrl: config.metaDataUrl,
         client_id: config.clientId,
-        redirect_uri: baseUrl + '/#/oidc-callback',
+        redirect_uri: baseUrl + '#/oidc-callback',
         response_type: 'code', // code triggers auth code grant flow
         response_mode: 'query',
         scope: 'openid profile offline_access',
         monitorSession: false,
         post_logout_redirect_uri: baseUrl,
-        silent_redirect_uri: baseUrl + '/#/oidc-silent-redirect',
+        silent_redirect_uri: baseUrl + '#/oidc-silent-redirect',
         accessTokenExpiringNotificationTime: 10,
         automaticSilentRenew: false,
         filterProtocolClaims: true,
```

fixes that for me

**Pull request merged**
