### PR TITLE
Fix breadcrumb last element

### PR DESCRIPTION
**Pull request by kulmann**
## Description
This PR removes the anchor on the last breadcrumb segment.

## Related Issue
- Fixes https://github.com/owncloud/phoenix/issues/3722
- Partly fixes https://github.com/owncloud/phoenix/issues/1883

## Motivation and Context
Comply with common sense

## How Has This Been Tested?
- locally in chrome and firefox
- [ ] drone

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by kulmann** [comment]
cc @refs

**Comment by refs** [comment]
👏 if everyone is okay with this and it doesn't suppose an integrity problem with styles I'm cool with it

**Comment by kulmann** [comment]
> 👏 if everyone is okay with this and it doesn't suppose an integrity problem with styles I'm cool with it

Maybe there are tests related to it.. let's wait for drone.

**Comment by kulmann** [comment]
Test failures 😅 looking into it after lunch...

**Comment by kulmann** [comment]
Was just an xpath selector issue. Didn't find the last breadcrumb segment anymore. That is fixed now (CI currently running).

**Pull request merged**
