### PR TITLE
Downgrade vuex-persist to 2.0.1 to fix IE11 issues

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
See https://github.com/championswimmer/vuex-persist/issues/138 - 2.1.0 is not working in IE11

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by LukasHirt** [comment]
Tests again failed due to timeout. Restarting

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRenameFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5132/

<p>









































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5134/

<p>





</p></details>

**Comment by hoophony** [comment]
@DeepDiver1975 I changed the version to 2.0.1, but the issues still exists in ie about "unable to get undefined or null referenced property "toLowerCase""

**Comment by DeepDiver1975** [comment]
Since this pr is merged you can simply build Phoenix from master branch now

**Comment by hoophony** [comment]
@DeepDiver1975 Thank you very much,I have solved the problem after deleting the file named .cache in node_modules.

**Pull request merged**
