### PR TITLE
Added custom role

### LINKED ISSUE #1186: Collaborators tweaks after review
Moved to https://github.com/owncloud/enterprise/blob/master/product/oc10/index.md#collaborators

# Tasks

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Added custom role in collaborators to allow selecting specific permissions.

## Related Issue

- Fixes #1186 

## How Has This Been Tested?

- test environment: Manually

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
- [ ] when switch from custom role to another role at least one check box remains
Screenshot from 2019-07-25 09-14-50

**Comment by DeepDiver1975** [comment]
- [ ] a custom role is no longer displayed as customer role on reload - maybe because the permissions match up an existing role?
Screenshot from 2019-07-25 09-19-49
Screenshot from 2019-07-25 09-19-31

**Comment by LukasHirt** [comment]
> * [ ]  a custom role is no longer displayed as customer role on reload - maybe because the permissions match up an existing role?
>   Screenshot from 2019-07-25 09-19-49
>   Screenshot from 2019-07-25 09-19-31

Yes, since we map the roles from the permissions, it can happen really easily that user selects permissions matching other role and it then gets overwritten. Not sure if we can prevent this.

**Comment by LukasHirt** [comment]
> * [ ]  I'm not really happy with the switcher component - it is not really clear what means on and what means off. We either use checkboxes or give the switcher a cleaner visual
> 
> see https://vuetifyjs.com/en/components/selection-controls#switches-boolean
> 
> Screenshot from 2019-07-25 09-26-05
> Screenshot from 2019-07-25 09-26-00

Agree. Will adjust in ODS :wink:

**Comment by LukasHirt** [comment]
@DeepDiver1975 ODS upgraded so switches are now looking at least a little bit better.

image

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUILogin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4420/4

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4443/9

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4443/13

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4443/12

<p>





</p></details>

**Pull request merged**
