### PR TITLE
Added drag and drop

### LINKED ISSUE #880: file drop support
### Scenario
As a user I want to drag files and folders from my desktop file manager into phoenix

### Expectation
- single files can be dropped
- multiple files can be dropped
- folders can be dropped
- full folder structures INCLUDING empty folders can be dropped
- the dropzone is the whole files app place in the browser

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Added support for drag and drop and moved upload into mixins so it can be used by it without duplicating the functions. First needs to be merged oc-dropzone component in ods.

## Related Issue

- Fixes #880 

## How Has This Been Tested?

- test environment: Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Edit upload function to accept folders
- [x] Merge oc-dropzone component in ods
- [ ] Add transition (default transition from vue glitches)

### CODE REVIEW

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2468/

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2494/

**Comment by felixheidecke** [comment]
I guess `vue2-dropzone` dependency is missing.

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2500/

**Pull request merged**
