### PR TITLE
Quick workaround: Disable file/folder renaming for all views

### LINKED ISSUE #1750: Not possible to rename a file on the favorites page to a name of a file from an other folder
### Steps to reproduce
1. favorite file `folder/file1.txt`
1. favorite file `folder2/file2.txt`
1. navigate to the favorite page
1. try to rename `folder/file1.txt` to `file2.txt`

### Expected behaviour
renaming should be possible, because there is no conflict

### Actual behaviour
renaming is not possible, the UI claims that filename `file2.txt` is taken

### LINKED ISSUE #1760: file names are not visible in trashbin page while browsing through mobile phone
### Steps to reproduce
Using your mobile phone:-
1. Delete some files and browse to the trashbin page.
   Here file name is not displayed
 

2. Also you have to scroll right to get restore option, which is not a good design
  

### Expected behaviour
File name must be displayed in trashbin

### Actual behaviour
File name is not properly displayed in trashbin

### PR DESCRIPTION
**Pull request by Julian1998**
## Description

Disallow all renames

## Related Issue

- Fixes #1750 

## Motivation and Context

@DeepDiver1975 requested a workaround as described in #1750. There it is :)

## How Has This Been Tested?

- Try to rename a file
- Rename button should be disabled

## Screenshots (if appropriate):
Bildschirmfoto von »2019-09-10 15-55-56«

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRenameFolders</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5052/

<p>



















































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5052/

<p>









</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5052/

<p>







































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5052/

<p>








































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRenameFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/5052/

<p>





















































































































</p></details>

**Comment by LukasHirt** [comment]
@Julian1998 Is the related and then in motivation issue right one?

**Comment by LukasHirt** [comment]
If it's related to #1750 then disable pls only on favorites view and leave it in the "main" files list.

**Comment by Julian1998** [comment]
fixed in #https://github.com/owncloud/phoenix/pull/2129

**Pull request closed without merging**
