### PR TITLE
WIP: add logic for extended topbar

### PR DESCRIPTION
**Pull request by scramb**
## Description

Added same logic for loading topbar-addons as for sidebar tabs. Topbar will extend if active app has exposed a valid topbar. As allways design is tbd. 
This will work better with list then with datatable.

## Motivation and Context

As discussed in UX workshop TopNavigation should be fixed to the top.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Technical debt

## Checklist:

- [x] Code changes

## Open tasks:

- [ ] fix content position
- [ ] refactor redundant function calls, like filteredFiles
- [ ] merge with alternative file list from @DeepDiver1975 
- [ ] add markdown-editor topbar, maybe @tempelgogo

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:see_no_evil: 

screenshot from 2018-12-14 08-32-18

**Comment by DeepDiver1975** [comment]
screenshot from 2018-12-14 08-33-45

**Comment by DeepDiver1975** [comment]
can a app have no top bar? this shall be supported as well ...

**Comment by DeepDiver1975** [comment]
> can a app have no top bar? this shall be supported as well ...

hmmm ... app area seems to be miss placed ...
screenshot from 2018-12-14 08-35-44

**Comment by scramb** [comment]
Will resolve issues and work on another method someone came up with at 35c3

**Pull request closed without merging**
