### PR TITLE
We shall only call the sso end session endpoint in case we still have…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… the id_token. In some sceanrios the id_token is no longer known (expiry)

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I guess the test scenarios need to be adjusted ....

**Comment by LukasHirt** [comment]
The problem with tests is that logout leads us to "Access denied" page. Not sure if this is happening also in a setup with oidc provider or only with oauth2.

**Comment by LukasHirt** [comment]
The access denied page is appearing because of this line https://github.com/owncloud/phoenix/blob/f4eeac80a042b1d6ea4f72f004627e7631bc9476/src/store/user.js#L110 Would it be fine using here "Login" page instead or removing completely @DeepDiver1975 ? Can the user be unloaded because of some error? Or is it only when doing a logout? I guess also expiration? But even then I'd still expect to see login screen instead if I'd be the user.

**Comment by kulmann** [comment]
> The access denied page is appearing because of this line
> 
> https://github.com/owncloud/phoenix/blob/f4eeac80a042b1d6ea4f72f004627e7631bc9476/src/store/user.js#L110
> 
> Would it be fine using here "Login" page instead or removing completely @DeepDiver1975 ? Can the user be unloaded because of some error? Or is it only when doing a logout? I guess also expiration? But even then I'd still expect to see login screen instead as a user.

As a bonus you would come back to the route where you were before the logout (also in case of expiration), right? As of now you come back to the access denied route when you re-login after expiration.

**Comment by DeepDiver1975** [comment]
> Would it be fine using here "Login" page instead or removing completely @DeepDiver1975 ? Can the user be unloaded because of some error? Or is it only when doing a logout? I guess also expiration? But even then I'd still expect to see login screen instead as a user.

in the very first implementation we always redirected to the login screen - this was changed upon customer request.

I find it rather complicated to differentiate when to display which page .... :see_no_evil:

**Comment by DeepDiver1975** [comment]
> Changelog pls

added

**Comment by LukasHirt** [comment]
Hmm, looking at https://drone.owncloud.com/owncloud/phoenix/9041 the ocis tests seems to perform better than here. Maybe it is after all related somehow to this PR?

**Comment by DeepDiver1975** [comment]
>  Maybe it is after all related somehow to this PR?

seems to be - who has enough understanding on having a look? I lost track with ocis these days :see_no_evil:

**Comment by LukasHirt** [comment]
> who has enough understanding on having a look?

@dpakach Would you have time to take a look at the ocis tests here?

**Comment by dpakach** [comment]
> @dpakach Would you have time to take a look at the ocis tests here?

@LukasHirt I will try to run them locally and see what's going on

**Comment by dpakach** [comment]
All tests are failing on login so seems like something has changed in login flow

**Comment by dpakach** [comment]
Sorry, l am unable to reproduce this locally. I just rebased just to see what happens.

**Comment by LukasHirt** [comment]
> All tests are failing on login so seems like something has changed in login flow

The changes are actually in the opposite - logout.

> Sorry, l am unable to reproduce this locally. I just rebased just to see what happens.

It's green now, I'll try to run them one more time and if they'll still be green I'll merge it :wink: Thanks a lot for taking a look!

**Pull request merged**
