### PR TITLE
Add step to build oauth2 app in ci

### LINKED ISSUE #2383: CI failing when `php occ oauth2:add-client Phoenix`
e.g. https://drone.owncloud.com/owncloud/phoenix/6181/2/10
```
+ php occ a:e oauth2
oauth2 enabled
+ php occ oauth2:add-client Phoenix Cxfj9F9ZZWQbQZps1E1M0BszMz6OOFq3lxjSuc8Uh4HLEYb9KIfyRMmgY5ibXXrU 930C6aA0U1VhM03IfNiheR2EwSzRi4hRSpcNqIhhbpeSGU6h38xssVfNcGP0sSwQ http://phoenix/oidc-callback.html
PHP Fatal error:  require_once(): Failed opening required '/var/www/owncloud/apps/oauth2/lib/../vendor/autoload.php' (include_path='/var/www/owncloud/apps:/var/www/owncloud/apps-external') in /var/www/owncloud/apps/oauth2/lib/Utilities.php on line 22
```

This will be due to `oauth2` PR https://github.com/owncloud/oauth2/pull/229 that was merged yesterday. `oauth2` now needs `make vendor` after cloning from git.

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Add step `make vendor` in CI to build the oauth2 app.

## Related Issue

- Fixes #2383

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6185/

<p>






































</p></details>

**Comment by DeepDiver1975** [comment]
We should switch over to use real releases from the oauth App.

**Comment by phil-davis** [comment]
> We should switch over to use real releases from the oauth App.

Yes, that would be better. @dpakach you guys can look into that for a next PR.

For now, this PR will get CI  green again.

**Comment by phil-davis** [comment]
I restarted drone because of an unrelated error. Hopefully we get green CI this time!

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Trashbin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6189/

<p>












































</p></details>

**Comment by phil-davis** [comment]
Restarted drone again. It is struggling to get a full clean run today.

**Comment by DeepDiver1975** [comment]
Relevant jobs did succeed -> merge

**Pull request merged**
