### PR TITLE
[Tests-Only] group test suites in drone to improve test runtime

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Group the CI pipelines in drone to improve the overall runtime.

## Related Issue

- Fixes Drone agent not being available when there are many builds running at same time.

## Motivation and Context

Since there is no  easy way to share the build products between pipelines, each pipeline has to run a very long setup process to set up the system under test. This make the overall runtime of the CI very long. By grouping the suites that have very less tests, we can run multiple suites on a same build process. 

## How Has This Been Tested?

:robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [x] CI

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by phil-davis** [comment]
@dpakach looks OK. There is now a conflict to be resolved.

**Comment by dpakach** [comment]
@phil-davis rebased

**Review by phil-davis — APPROVED** [review]
LGTM - please look at the drone logs and check that the expected scenarios did actually run in each pipeline.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/phoenix/11224/4/19 webUIBasic 17 min
https://drone.owncloud.com/owncloud/phoenix/11224/5/19 webUICreateDelete 24 min
https://drone.owncloud.com/owncloud/phoenix/11224/6/19 webUIRename 32 min
https://drone.owncloud.com/owncloud/phoenix/11224/7/19 webUISharingBasic 27 min
Looks good.

**Pull request merged**
