### PR TITLE
Build and install core & apps from node

### PR DESCRIPTION
**Pull request by scramb**
## Changes
- `npm install` does this now recursive for all apps
- `npm install` does now include an initial build for all apps & core
- less is build from npm aswell

## To-Do
- update Drone to use node:10 image and new build procedure
- yarn?

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
browser error when listing files:

screenshot from 2018-10-31 12-02-26

**Comment by DeepDiver1975** [comment]
spawns the server now with https - how can thie be changed? THX

**Comment by scramb** [comment]
> spawns the server now with https - how can thie be changed? THX

in the webpack.dev.js but this shouldn't be there - just testing ;) would default this false.

**Comment by scramb** [comment]
Gonna rebase and fix this...

**Pull request closed without merging**
