### PR TITLE
Updated all deps

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Comment by PVince81** [comment]
CI failure on the linter, maybe some of the rules got implicitly stricter ?

**Comment by LukasHirt** [comment]
> CI failure on the linter, maybe some of the rules got implicitly stricter ?

Strange, this should have failed already in the previous CIs. I'll fix it

**Comment by LukasHirt** [comment]
@PVince81 Removed the unused var

**Comment by LukasHirt** [comment]
Tests are failing with timeout - will investigate

**Comment by LukasHirt** [comment]
Locally doesn't pass the test for me even on master 🤢

**Comment by LukasHirt** [comment]
Maybe found a reason - nightwatch upgrade slipped in. Reverted to prev version. Let's see if it will pass now.

Locally still not working but because of some issue with my setup. Will need to see what causes that.

**Pull request merged**
