### PR TITLE
Update to babel 7 and add browserlist to get support for Edge

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
- [x] Update to babel 7
- [x] introduce browserslist

## Related Issue
- #546 

## Screenshots
edge-works

## How Has This Been Tested?
- [x] :hand: with edge
- [ ] :hand: with ie

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] fix logo to be displayed in edge
- [ ] fix ie - error below

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
- [ ] promise/catch polyfill is Missing for ie11

**Comment by DeepDiver1975** [comment]
svg upstream issue has been opened: https://github.com/vuetifyjs/vuetify/issues/6316

**Comment by DeepDiver1975** [comment]
I propose to fix IE in a separate PR ... this seems to be a bigger task.

**Comment by DeepDiver1975** [comment]
@scramb please review I'd like to merge this as of now to get this finished in this sprint - THX

**Comment by scramb** [comment]
as far as i could test (edge) this works properly

**Pull request merged**
