### PR TITLE
deps 20191107

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Updating dependencies

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6233/

<p>











</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6233/

<p>







</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>iPhone</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6233/

<p>







</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6240/

<p>











</p></details>

**Comment by phil-davis** [comment]
Failing again, e.g. https://drone.owncloud.com/owncloud/phoenix/6240/2/14
This is "just" a dependency update PR, so it "should" pass easily :)
@dpakach can you get someone to try this out locally and see if there are real things that fail.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6240/

<p>







</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>iPhone</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6240/

<p>



























</p></details>

**Comment by skshetry** [comment]
https://github.com/nightwatchjs/nightwatch/commit/0beacadcdcf17837371a0c0c6e616bb7ec48ee8c fixed a bug in v1.2.3. We were relying on `isVisible` not throwing an error when the element is not visible when it should have. Now, with the fix, it throws an error instead of boolean. @dpakach  is working on adjusting the "assumptions".

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Trashbin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6253/

<p>

































</p></details>

**Comment by PVince81** [comment]
known random failure: known random failure: https://github.com/owncloud/phoenix/issues/1728

**Pull request merged**
