### PR TITLE
Sidebar now select multiple correctly and style fix

### PR DESCRIPTION
**Pull request by scramb**
## Description

Sidebar now select multiple correctly and shows buttons for basic actions like share download and delete - if selected multiple download is disabled for now.
## Related Issue

N/A
## Motivation and Context

N/A
## How Has This Been Tested?

-

## Screenshots (if appropriate):
2018-11-26-131436_1917x900_scrot
2018-11-26-131423_1921x900_scrot

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Fix Sidebar Headline

### CODE REVIEW

**Comment by scramb** [comment]
you mean full height of screen? guess we can do this

**Comment by DeepDiver1975** [comment]
> you mean full height of screen? guess we can do this

yes - thx

**Comment by DeepDiver1975** [comment]
conflicting because of #356 being merged ....

**Comment by DeepDiver1975** [comment]
- changing folder keeps sidebar open with the previous selection
- the share action will come from an app - people like to disable sharing ....

**Comment by scramb** [comment]
@rebased to #359 and closed

**Pull request closed without merging**
