### PR TITLE
Display files list only if there is at least one item

### LINKED ISSUE #2726: Warning related to virtual scroll
image

appearing in the console when opening the files app

master e9dced79b6a8da066055d40627024d3ad6494561

### PR DESCRIPTION
**Pull request by LukasHirt**
## Related Issue

- Fixes #2726

## How Has This Been Tested?

- test environment: Manually
- test case 1: Check console in all files page

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by PVince81** [comment]
Might overlap somehow with #1911 but would do for the short term

**Comment by LukasHirt** [comment]
Hmm, the error is still showing up when switching between different lists. Will investigate.

**Comment by LukasHirt** [comment]
> Hmm, the error is still showing up when switching between different lists. Will investigate.

Found the issue. Was due to some troubles with the load of the folder. The mounted point was too late. It then got confused between wrong items. Solved with beforeMount.

**Comment by LukasHirt** [comment]
@PVince81 Can you pls re-review? There is the change from mounted to beforeMount. Let me pls know if you're okay with that change.

**Pull request merged**
