### PR TITLE
Display collaborators type

### LINKED ISSUE #3804: Show username of users when sharing
When I want to share something with a user, I can search for him but the list only contains the display names.
In large institutions we might have multiple users with the same name, therefore we need a way to distinguish them. It would be great to see the usernames (or, in some cases, emails) in this list, since the user pictures might not even be available.

This information is already being sent in the reply from the API.

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
We've added a new line into the collaborators autocomplete and list in the sidebar to display their type.

## Related Issue

- Closes #3804

## Screenshots (if appropriate):
image
image

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
Looking at the screenshot in your PR description, I would very much like to have consistency in the way how the email address is displayed in the autocomplete list item and the list of people you shared with. I.e. autocomplete list item should have the meta-style (grayed out) email address behind the username.

**Comment by LukasHirt** [comment]
> Looking at the screenshot in your PR description, I would very much like to have consistency in the way how the email address is displayed in the autocomplete list item and the list of people you shared with. I.e. autocomplete list item should have the meta-style (grayed out) email address behind the username.

Sorry, was a wrong screenshot 🤦  Updated

**Comment by kulmann** [comment]
Thanks :-) Is it a quick win to also fix the width of the autocomplete list item?

**Comment by micbar** [comment]
@LukasHirt Can we move this forward? WIP limit ;-)

**Comment by LukasHirt** [comment]
> Can we move this forward? WIP limit ;-)

Sure, will take care of it tomorrow :wink:

**Comment by LukasHirt** [comment]
@kulmann Width of autocomplete fixed and adjusted a selector in the tests so they should pass now.

**Review by kulmann — APPROVED** [review]
🚀

**Pull request merged**
