### PR TITLE
ownCloud 10 apps require a different tar layout - we build two differ…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…ent tar balls now

@LukasHirt let there be two tar balls on release now ... :man_shrugging:

### CODE REVIEW

**Comment by LukasHirt** [comment]
Hmm, makefile still generates only one tar ball for me here in release

**Comment by DeepDiver1975** [comment]
> Hmm, makefile still generates only one tar ball for me here in release

mind pasting the output? --transform is only available on gnu tar - mac has bsd? tar or something ...

**Comment by LukasHirt** [comment]
```
cp -R appinfo /Users/lukashirt/phoenix/dist
cp -R img /Users/lukashirt/phoenix/dist
cp .htaccess /Users/lukashirt/phoenix/dist
cp config.json.dist /Users/lukashirt/phoenix/dist/config.json
Skipping signing, either no key and certificate found in /Users/lukashirt/.owncloud/certificates/phoenix.key and /Users/lukashirt/.owncloud/certificates/phoenix.crt or occ can not be found at /Users/lukashirt/phoenix/../../occ
make: Circular create-release-folder <- create-release-folder dependency dropped.
rm -rf /Users/lukashirt/phoenix/release
mkdir /Users/lukashirt/phoenix/release
cd /Users/lukashirt/phoenix/dist && tar -czf /Users/lukashirt/phoenix/release/phoenix.tar.gz --exclude=appinfo -C /Users/lukashirt/phoenix/dist * .htaccess
rm -rf /Users/lukashirt/phoenix/phoenix
mkdir /Users/lukashirt/phoenix/phoenix
cp -R /Users/lukashirt/phoenix/dist /Users/lukashirt/phoenix/phoenix
tar -czf /Users/lukashirt/phoenix/release/phoenix-app.tar.gz --transform s/dist/phoenix/ -C phoenix dist
tar: Option --transform is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
make: *** [package-ocx] Error 1

**Comment by LukasHirt** [comment]
Also, a folder called phoenix with dist subfolder is created in the root. Is that supposed to happen?

**Comment by LukasHirt** [comment]
When doing tar ball manually I run:

`tar -czvf <tar_file> <target_folder>`

**Comment by DeepDiver1975** [comment]
> tar -czf /Users/lukashirt/phoenix/release/phoenix-app.tar.gz --transform s/dist/phoenix/ -C phoenix dist
> tar: Option --transform is not supported
> Usage:

not supported on your system :man_shrugging:

**Comment by DeepDiver1975** [comment]
:see_no_evil: https://brewinstall.org/Install-gnu-tar-on-Mac-with-Brew/ :rofl:

**Comment by LukasHirt** [comment]
> 🙈 https://brewinstall.org/Install-gnu-tar-on-Mac-with-Brew/ 🤣

Yeah, just saw it as well :grin: Already installing

**Comment by LukasHirt** [comment]
There is still the phoenix folder in root though... feels rather strange :shrug:

**Pull request merged**
