### PR TITLE
File upload feature

### PR DESCRIPTION
**Pull request by OshanIvantha**
Currently the js-owncloud-client doesn't seem to support getting upload progress while uploading.

### CODE REVIEW

**Comment by PVince81** [comment]
please extend js-owncloud-client if possible to add missing features instead of working around

**Comment by felixheidecke** [comment]
> please extend js-owncloud-client if possible to add missing features instead of working around

@PVince81 still possible within the timeframe?

**Comment by PVince81** [comment]
I predict some major difficulties, knowing how complex the old jquery.fileupload is in regards to uploading, progress report and chunking. We can focus on non-chunked uploads at first.

**Comment by OshanIvantha** [comment]
This PR only contains the upload progress bar functionality. 
File upload has yet to be implemented as the uploading functionality in js-owncloud-client for browsers doesn't seem to work even in the non-chunked mode.

**Comment by felixheidecke** [comment]
> File upload has yet to be implemented as the uploading functionality in js-owncloud-client for browsers doesn't seem to work even in the non-chunked mode.

Does that mean that this PR failed in its purpose?

**Comment by OshanIvantha** [comment]
Yeah. Its not a PR to be merged.

**Comment by felixheidecke** [comment]
😿

**Pull request closed without merging**
