### PR TITLE
[DONOTMERGE] Run failing tests more often

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
For testing, `findItemInFilesList` is used to locate those resource in webUI viewport which have to be scrolled.
Inside function `findItemInFilesList` two wrapper elements were used, and different were used to calculate `scrollDistance` and `visiblePosition`
This PR removes un-necessary wrapper defined inside the function and use functional wrapper element.

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsers7</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/8535/

<p>




</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsers1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/8535/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsers8</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/8535/

<p>




</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsers6</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/8535/

<p>




</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsers4</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/8535/

<p>




</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsers5</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/8535/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsers3</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/8535/

<p>




</p></details>

**Comment by kiranparajuli589** [comment]
Drone passed: https://drone.owncloud.com/owncloud/phoenix/8557
@individual-it

**Comment by kiranparajuli589** [comment]
Closing this, as it was created just for testing

**Pull request closed without merging**
