### PR TITLE
Make file previews properly fit

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Fix file preview to prevent overflowing vertically and also added CSS
property to make sure the ratio is preserved.

## Related Issue
Fixes https://github.com/owncloud/product/issues/232

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by PVince81** [comment]
Before:
image

After:
image

**Review by LukasHirt — APPROVED** [review]
Nice! :rocket: There were also some ideas about cropping images in the thumbnails service. Maybe later if that will be done this would need to be checked.

**Comment by PVince81** [comment]
Yeah, intelligent cropping could be cool.

Please note that here this problem also happens with OC 10, so it's independent from the backend so fits well as a generic fix.

**Comment by PVince81** [comment]
fun stuff...
image

job restarted

**Pull request merged**
