### PR TITLE
Catch console errors in CI

### LINKED ISSUE #2728: Make CI fail when warnings in console
We should trigger a CI failure whenever we detect warnings in the browser console at the end of any successful test.

If this is too complicated to do technically, then at least add scenarios for the main pages like the files app, public link page and files drop.

This way we can catch these earlier as they could be signs of regressions.

@individual-it @DeepDiver1975 @LukasHirt

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Catch console errors in CI at the end of every test.
If any errors are found, the test will fail and the offending messages are printed out.

## Related Issue
Fixes #2728 

## How Has This Been Tested?
Manual test with master, since we have console errors there already...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] rebase after the actual errors have been fixed:
   - [ ] after: https://github.com/owncloud/phoenix/pull/2727
   - [ ] after: https://github.com/owncloud/phoenix/issues/2726

**Comment by PVince81** [comment]
Screenshot_20191217_161221

**Comment by skshetry** [comment]
@PVince81, there's conflict as I just refactored `nightwatch.conf.js` and merged two `setup-*` to only have single entry-points.

**Comment by skshetry** [comment]
@PVince81, #2756 implemented most of the changes from this PR. I have adjusted this PR to fail the tests when there is `console.error`.

**Comment by LukasHirt** [comment]
Rebased PR after https://github.com/owncloud/phoenix/issues/2726 has been merged.

**Comment by individual-it** [comment]
the missing avatar seems to be an issue: `3:25:01 PM - SEVERE - http://owncloud/remote.php/dav/avatars/user1/128.png - Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/phoenix/issues/2977 for the avatar errors

**Comment by PVince81** [comment]
Rebased and adjusted as follows:
- SEVERE log entries are always retrieved.
- in case of test failure, also include DEBUG messages
- if at least one message was found, fail the test

**Comment by PVince81** [comment]
if we still need this, this will need to be redone

**Pull request closed without merging**
