### PR TITLE
Dialog prompt message fix

### PR DESCRIPTION
**Pull request by kulmann**
## Description
Make error messages in dialog prompts less annoying.
Within the dialog prompt for several small tasks (e.g. creating a new folder) there are three things changed:
1. the error message is now shown below the input field, using new properties from `oc-text-input` in ODS.
2. the changes on error messages are debounced for 400 milliseconds. As a result error messages that would appear during typing (like if you type a folder name which contains a blank in between two words) are not shown at all (if you type more than 1 character every 400 milliseconds).

## Related Issue

- Fixes https://github.com/owncloud/phoenix/issues/1906

## Motivation and Context
UX improvement

## Screenshots (if appropriate):
jumpy error message gone

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by LukasHirt** [comment]
Pls post a screenshot into description

**Comment by LukasHirt** [comment]
It still feels strange since the dialog is still kind of "jumpy". Just in a different way.

I'd still say that a solution like this would be better way to go:

image

**Comment by kulmann** [comment]
@LukasHirt @PVince81 using the feature from here https://github.com/owncloud/owncloud-design-system/pull/690 the input prompt looks like in the screenshots below. Vertical space is reserved, modal layout doesn't jump anymore, except on long messages that break into a second line. What do you think?

Bildschirmfoto 2020-03-24 um 18 23 02
Bildschirmfoto 2020-03-24 um 18 23 20

**Comment by LukasHirt** [comment]
IMHO this looks much better 👍

**Comment by LukasHirt** [comment]
Agh, tests failing 🤢 Can you take a look? @kulmann

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCIS</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/9120/

<p>

















































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCIS</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/9122/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIOCIS</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/9302/

<p>







</p></details>

**Pull request merged**
