### PR TITLE
@babel/core7 and @babel/polyfill, add Browserslist

### PR DESCRIPTION
**Pull request by scramb**
Originial PR #553 

Basically the same, lost the trace and did it again.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
From my understanding you are missing one important point: 
https://github.com/owncloud/phoenix/pull/553/files#diff-659af4641d8d19d971c143583c5b437eR1

This is required from my understanding to pull in the proper polyfills ....

Anyway - I don't understand why you are redoing the while PR ...

**Comment by scramb** [comment]
im not sure if this is correct as far as i got while reading in all of those polyfill things `@babel/polyfill` should include those and they get wrapped into bundle by babel-loader. I'll  close this one if we can fiddle this mess i made in your PR. I just got mad since i messed up your PR and wanted to fix this so badly.

**Comment by DeepDiver1975** [comment]
I got one step closer in ma PR by removing axios which does not work on IE11 ..... rest should be fine afaik ....

**Comment by scramb** [comment]
then i'll close this one - and we discuss the core-js thing further since this should be included by the right use of `@babel/polyfill`

**Pull request closed without merging**
