### PR TITLE
Use elipsis character instead of 3 dots

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
The elipsis character shall be used in favor for 3 dots.

## Motivation and Context
Have proper text

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2401/

**Comment by LukasHirt** [comment]
Doesn't it need to be changed then also in translations.json?

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2405/

**Comment by DeepDiver1975** [comment]
> Doesn't it need to be changed then also in translations.json?

Tests are executed for English - the original string in source code are used.

@LukasHirt please review and approve - drone is green now. THX

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2464/

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2467/

**Comment by DeepDiver1975** [comment]
:confused: 

```
 Error while running .clickElement() protocol action: element click intercepted: Element <button aria-label="Delete" class="oc-button uk-button-default">...</button> is not clickable at point (913, 813). Other element would receive the click: <div id="delete-file-confirmation-dialog" uk-modal="" class="uk-modal" style="display: block;">...</div>

    ✖ failed
      Error while running "click" command: this.reporter.registerTestError is not a function
      Error while running "click" command: this.reporter.registerTestError is not a function
      Error while running "click" command: this.reporter.registerTestError is not a function
      TypeError: Error while running "click" command: this.reporter.registerTestError is not a function
          at transport.locateElement.then.then.catch.result (/var/www/owncloud/phoenix/node_modules/nightwatch/lib/api-loader/element-command.js:138:25)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:189:7)
Then as "user1" folder "simple-folder" should not exist

**Pull request merged**
