### PR TITLE
Upgrade deps 20191009

### PR DESCRIPTION
**Pull request by DeepDiver1975**
yarn upgrade-all

### CODE REVIEW

**Comment by LukasHirt** [comment]
shall we maybe wait with this until we have IE tests? Or manual testing of IE for this PR for now?

**Comment by DeepDiver1975** [comment]
> shall we maybe wait with this until we have IE tests? Or manual testing of IE for this PR for now?

I can do a manual ie test ...

**Comment by DeepDiver1975** [comment]
> I can do a manual ie test ...

IE is fine @LukasHirt

**Comment by DeepDiver1975** [comment]
> Seems that yarn.lock is missing for core.

there are no updates to it :man_shrugging:

**Comment by LukasHirt** [comment]
> there are no updates to it 🤷‍♂

Strange, dependabot is trying to do some. E. g. #2165 #2166 #2188

**Comment by DeepDiver1975** [comment]
aha ..
```
✔ deepdiver:phoenix [ deps/20191009 ✭ | …6 ⚑ 102 ] ➭ yarn upgrade
yarn upgrade v1.19.1
[1/4] Resolving packages...
error Couldn't find match for "issue-727-retry" in "refs/heads/1.x,refs/heads/2.x,refs/heads/3.x,refs/heads/4.x,refs/heads/Izhaki-add-cucumber-expressions-to-step-definitions,refs/heads/Izhaki-patch-1,refs/heads/add-babel-rc-to-cli-docs,refs/heads/add-node-11-to-build,refs/heads/cr-ci,refs/heads/cr-deps-gherkin,refs/heads/cr-shared,refs/heads/cr-tagsOr,refs/heads/cr-tty,refs/heads/cr-typescript,refs/heads/cucumber-ltd,refs/heads/daspr2-feature/typescript-defs,refs/heads/doc-cli-transpilation-improvements,refs/heads/docs-various,refs/heads/functional-api-take-2,refs/heads/gh-pages,refs/heads/master,refs/heads/node12,refs/heads/snyk-fix-8e0a7cf72ad8a20409a00ce58e65157d,refs/heads/snyk-fix-bztquj,refs/pull/100/head,refs/pull/100/merge,refs/pull/1002/head,refs/pull/1003/head,refs/pull/1005/head,refs/pull/1006/head,refs/pull/1006/merge,refs/pull/1008/head,refs/pull/1018/head,refs/pull/1020/head,refs/pull/1022/head,refs/pull/1023/head,refs/pull/1024/head,refs/pull/1028/head,refs/pull/103/head,refs/pull/103/merge,refs/pull/1030/head,refs/pull/1033/head,refs/pull/1033/merge,refs/pull/1039/head,refs/pull/104/head,refs/pull/104/merge,refs/pull/1041/head,refs/pull/1047/head,refs/pull/1047/merge,refs/pull/1048/head,refs/pull/1051/head,refs/pull/1052/head,refs/pull/1053/head,refs/pull/1055/head,refs/pull/1056/head,refs/pull/1058/head,refs/pull/1058/merge,refs/pull/106/head,refs/pull/106/merge,refs/pull/1064/head,refs/pull/1065/head,refs/pull/1069/head,refs/pull/1069/merge,refs/pull/1080/head,refs/pull/1081/head,refs/pull/1082/head,refs/pull/1084/head,refs/pull/1084/merge,refs/pull/1088/head,refs/pull/109/head,refs/pull/109/merge,refs/pull/1093/head,refs/pull/1099/head,refs/pull/1099/merge,refs/pull/1101/head,refs/pull/1103/head,refs/pull/1103/merge,refs/pull/111/head,refs/pull/111/merge,refs/pull/1113/head,refs/pull/1114/head,refs/pull/1115/head,refs/pull/1115/merge,refs/pull/1121/head,refs/pull/1123/head,refs/pull/1123/merge,refs/pull/1125/head,refs/pull/1126/head,refs/pull/1127/head,refs/pull/1131/head,refs/pull/1133/head,refs/pull/1134/head,refs/pull/1143/head,refs/pull/1151/head,refs/pull/1157/head,refs/pull/1158/head,refs/pull/116/head,refs/pull/116/merge,refs/pull/1161/head,refs/pull/1162/head,refs/pull/1165/head,refs/pull/117/head,refs/pull/117/merge,refs/pull/1171/head,refs/pull/1173/head,refs/pull/118/head,refs/pull/118/merge,refs/pull/1184/head,refs/pull/1186/head,refs/pull/1189/head,refs/pull/119/head,refs/pull/119/merge,refs/pull/1192/head,refs/pull/1193/head,refs/pull/1197/head,refs/pull/1198/head,refs/pull/1198/merge,refs/pull/1205/head,refs/pull/1211/head,refs/pull/1213/head,refs/pull/1214/head,refs/pull/1216/head,refs/pull/1216/merge,refs/pull/1219/head,refs/pull/122/head,refs/pull/1223/head,refs/pull/1225/head,refs/pull/1227/head,refs/pull/1227/merge,refs/pull/1228/head,refs/pull/1229/head,refs/pull/123/head,refs/pull/123/merge,refs/pull/1234/head,refs/pull/1239/head,refs/pull/1240/head,refs/pull/1240/merge,refs/pull/126/head,refs/pull/126/merge,refs/pull/130/head,refs/pull/130/merge,refs/pull/138/head,refs/pull/138/merge,refs/pull/139/head,refs/pull/139/merge,refs/pull/140/head,refs/pull/140/merge,refs/pull/141/head,refs/pull/141/merge,refs/pull/143/head,refs/pull/143/merge,refs/pull/148/head,refs/pull/148/merge,refs/pull/151/head,refs/pull/151/merge,refs/pull/154/head,refs/pull/154/merge,refs/pull/155/head,refs/pull/155/merge,refs/pull/156/head,refs/pull/156/merge,refs/pull/158/head,refs/pull/158/merge,refs/pull/161/head,refs/pull/161/merge,refs/pull/163/head,refs/pull/163/merge,refs/pull/168/head,refs/pull/168/merge,refs/pull/170/head,refs/pull/170/merge,refs/pull/171/head,refs/pull/171/merge,refs/pull/172/head,refs/pull/172/merge,refs/pull/173/head,refs/pull/173/merge,refs/pull/178/head,refs/pull/178/merge,refs/pull/183/head,refs/pull/183/merge,refs/pull/188/head,refs/pull/188/merge,refs/pull/189/head,refs/pull/189/merge,refs/pull/191/head,refs/pull/191/merge,refs/pull/192/head,refs/pull/193/head,refs/pull/193/merge,refs/pull/194/head,refs/pull/194/merge,refs/pull/196/head,refs/pull/196/merge,refs/pull/197/head,refs/pull/197/merge,refs/pull/199/head,refs/pull/199/merge,refs/pull/202/head,refs/pull/202/merge,refs/pull/204/head,refs/pull/204/merge,refs/pull/207/head,refs/pull/207/merge,refs/pull/210/head,refs/pull/210/merge,refs/pull/211/head,refs/pull/211/merge,refs/pull/214/head,refs/pull/214/merge,refs/pull/215/head,refs/pull/215/merge,refs/pull/216/head,refs/pull/216/merge,refs/pull/219/head,refs/pull/219/merge,refs/pull/220/head,refs/pull/223/head,refs/pull/223/merge,refs/pull/225/head,refs/pull/225/merge,refs/pull/226/head,refs/pull/226/merge,refs/pull/227/head,refs/pull/227/merge,refs/pull/228/head,refs/pull/228/merge,refs/pull/234/head,refs/pull/234/merge,refs/pull/235/head,refs/pull/235/merge,refs/pull/236/head,refs/pull/236/merge,refs/pull/238/head,refs/pull/238/merge,refs/pull/240/head,refs/pull/240/merge,refs/pull/243/head,refs/pull/243/merge,refs/pull/247/head,refs/pull/247/merge,refs/pull/25/head,refs/pull/25/merge,refs/pull/252/head,refs/pull/252/merge,refs/pull/253/head,refs/pull/253/merge,refs/pull/255/head,refs/pull/255/merge,refs/pull/256/head,refs/pull/257/head,refs/pull/257/merge,refs/pull/258/head,refs/pull/258/merge,refs/pull/270/head,refs/pull/270/merge,refs/pull/284/head,refs/pull/284/merge,refs/pull/287/head,refs/pull/287/merge,refs/pull/29/head,refs/pull/29/merge,refs/pull/291/head,refs/pull/291/merge,refs/pull/30/head,refs/pull/30/merge,refs/pull/303/head,refs/pull/303/merge,refs/pull/304/head,refs/pull/304/merge,refs/pull/308/head,refs/pull/308/merge,refs/pull/309/head,refs/pull/309/merge,refs/pull/31/head,refs/pull/31/merge,refs/pull/312/head,refs/pull/312/merge,refs/pull/315/head,refs/pull/315/merge,refs/pull/317/head,refs/pull/317/merge,refs/pull/334/head,refs/pull/334/merge,refs/pull/336/head,refs/pull/336/merge,refs/pull/337/head,refs/pull/337/merge,refs/pull/345/head,refs/pull/345/merge,refs/pull/348/head,refs/pull/348/merge,refs/pull/351/head,refs/pull/351/merge,refs/pull/352/head,refs/pull/352/merge,refs/pull/354/head,refs/pull/354/merge,refs/pull/358/head,refs/pull/358/merge,refs/pull/359/head,refs/pull/359/merge,refs/pull/360/head,refs/pull/360/merge,refs/pull/361/head,refs/pull/361/merge,refs/pull/364/head,refs/pull/364/merge,refs/pull/365/head,refs/pull/368/head,refs/pull/368/merge,refs/pull/37/head,refs/pull/37/merge,refs/pull/373/head,refs/pull/373/merge,refs/pull/374/head,refs/pull/374/merge,refs/pull/377/head,refs/pull/377/merge,refs/pull/381/head,refs/pull/381/merge,refs/pull/382/head,refs/pull/382/merge,refs/pull/383/head,refs/pull/383/merge,refs/pull/384/head,refs/pull/384/merge,refs/pull/385/head,refs/pull/385/merge,refs/pull/387/head,refs/pull/387/merge,refs/pull/398/head,refs/pull/398/merge,refs/pull/405/head,refs/pull/405/merge,refs/pull/406/head,refs/pull/406/merge,refs/pull/407/head,refs/pull/407/merge,refs/pull/410/head,refs/pull/410/merge,refs/pull/411/head,refs/pull/411/merge,refs/pull/412/head,refs/pull/412/merge,refs/pull/413/head,refs/pull/413/merge,refs/pull/414/head,refs/pull/414/merge,refs/pull/415/head,refs/pull/415/merge,refs/pull/416/head,refs/pull/416/merge,refs/pull/419/head,refs/pull/419/merge,refs/pull/420/head,refs/pull/420/merge,refs/pull/421/head,refs/pull/421/merge,refs/pull/422/head,refs/pull/422/merge,refs/pull/423/head,refs/pull/423/merge,refs/pull/424/head,refs/pull/424/merge,refs/pull/425/head,refs/pull/425/merge,refs/pull/426/head,refs/pull/426/merge,refs/pull/427/head,refs/pull/427/merge,refs/pull/428/head,refs/pull/428/merge,refs/pull/429/head,refs/pull/429/merge,refs/pull/431/head,refs/pull/431/merge,refs/pull/432/head,refs/pull/432/merge,refs/pull/434/head,refs/pull/434/merge,refs/pull/436/head,refs/pull/436/merge,refs/pull/442/head,refs/pull/442/merge,refs/pull/444/head,refs/pull/444/merge,refs/pull/448/head,refs/pull/448/merge,refs/pull/450/head,refs/pull/450/merge,refs/pull/451/head,refs/pull/451/merge,refs/pull/454/head,refs/pull/454/merge,refs/pull/455/head,refs/pull/455/merge,refs/pull/456/head,refs/pull/456/merge,refs/pull/457/head,refs/pull/457/merge,refs/pull/459/head,refs/pull/459/merge,refs/pull/462/head,refs/pull/462/merge,refs/pull/463/head,refs/pull/463/merge,refs/pull/464/head,refs/pull/464/merge,refs/pull/472/head,refs/pull/472/merge,refs/pull/474/head,refs/pull/474/merge,refs/pull/478/head,refs/pull/478/merge,refs/pull/479/head,refs/pull/479/merge,refs/pull/48/head,refs/pull/48/merge,refs/pull/481/head,refs/pull/482/head,refs/pull/482/merge,refs/pull/483/head,refs/pull/483/merge,refs/pull/484/head,refs/pull/484/merge,refs/pull/486/head,refs/pull/486/merge,refs/pull/489/head,refs/pull/489/merge,refs/pull/491/head,refs/pull/498/head,refs/pull/498/merge,refs/pull/501/head,refs/pull/501/merge,refs/pull/506/head,refs/pull/506/merge,refs/pull/508/head,refs/pull/508/merge,refs/pull/510/head,refs/pull/510/merge,refs/pull/511/head,refs/pull/511/merge,refs/pull/517/head,refs/pull/517/merge,refs/pull/521/head,refs/pull/521/merge,refs/pull/527/head,refs/pull/527/merge,refs/pull/529/head,refs/pull/529/merge,refs/pull/531/head,refs/pull/531/merge,refs/pull/536/head,refs/pull/539/head,refs/pull/539/merge,refs/pull/543/head,refs/pull/543/merge,refs/pull/544/head,refs/pull/544/merge,refs/pull/546/head,refs/pull/546/merge,refs/pull/548/head,refs/pull/548/merge,refs/pull/549/head,refs/pull/55/head,refs/pull/55/merge,refs/pull/555/head,refs/pull/556/head,refs/pull/557/head,refs/pull/557/merge,refs/pull/559/head,refs/pull/56/head,refs/pull/56/merge,refs/pull/562/head,refs/pull/566/head,refs/pull/566/merge,refs/pull/57/head,refs/pull/57/merge,refs/pull/571/head,refs/pull/573/head,refs/pull/573/merge,refs/pull/588/head,refs/pull/588/merge,refs/pull/589/head,refs/pull/59/head,refs/pull/59/merge,refs/pull/590/head,refs/pull/592/head,refs/pull/592/merge,refs/pull/595/head,refs/pull/605/head,refs/pull/606/head,refs/pull/606/merge,refs/pull/609/head,refs/pull/62/head,refs/pull/62/merge,refs/pull/621/head,refs/pull/628/head,refs/pull/633/head,refs/pull/633/merge,refs/pull/635/head,refs/pull/637/head,refs/pull/638/head,refs/pull/644/head,refs/pull/655/head,refs/pull/655/merge,refs/pull/659/head,refs/pull/660/head,refs/pull/661/head,refs/pull/664/head,refs/pull/665/head,refs/pull/665/merge,refs/pull/67/head,refs/pull/67/merge,refs/pull/677/head,refs/pull/680/head,refs/pull/680/merge,refs/pull/684/head,refs/pull/684/merge,refs/pull/685/head,refs/pull/685/merge,refs/pull/687/head,refs/pull/687/merge,refs/pull/688/head,refs/pull/688/merge,refs/pull/689/head,refs/pull/689/merge,refs/pull/69/head,refs/pull/69/merge,refs/pull/691/head,refs/pull/693/head,refs/pull/693/merge,refs/pull/694/head,refs/pull/694/merge,refs/pull/699/head,refs/pull/699/merge,refs/pull/700/head,refs/pull/700/merge,refs/pull/701/head,refs/pull/701/merge,refs/pull/703/head,refs/pull/704/head,refs/pull/704/merge,refs/pull/705/head,refs/pull/705/merge,refs/pull/706/head,refs/pull/706/merge,refs/pull/71/head,refs/pull/71/merge,refs/pull/711/head,refs/pull/711/merge,refs/pull/721/head,refs/pull/721/merge,refs/pull/722/head,refs/pull/726/head,refs/pull/73/head,refs/pull/73/merge,refs/pull/738/head,refs/pull/744/head,refs/pull/744/merge,refs/pull/75/head,refs/pull/752/head,refs/pull/752/merge,refs/pull/753/head,refs/pull/753/merge,refs/pull/76/head,refs/pull/76/merge,refs/pull/764/head,refs/pull/764/merge,refs/pull/766/head,refs/pull/766/merge,refs/pull/780/head,refs/pull/781/head,refs/pull/781/merge,refs/pull/788/head,refs/pull/788/merge,refs/pull/79/head,refs/pull/79/merge,refs/pull/793/head,refs/pull/794/head,refs/pull/794/merge,refs/pull/797/head,refs/pull/798/head,refs/pull/807/head,refs/pull/807/merge,refs/pull/810/head,refs/pull/810/merge,refs/pull/823/head,refs/pull/823/merge,refs/pull/827/head,refs/pull/828/head,refs/pull/828/merge,refs/pull/829/head,refs/pull/829/merge,refs/pull/83/head,refs/pull/83/merge,refs/pull/831/head,refs/pull/831/merge,refs/pull/833/head,refs/pull/838/head,refs/pull/841/head,refs/pull/853/head,refs/pull/853/merge,refs/pull/855/head,refs/pull/855/merge,refs/pull/857/head,refs/pull/86/head,refs/pull/86/merge,refs/pull/860/head,refs/pull/861/head,refs/pull/862/head,refs/pull/863/head,refs/pull/863/merge,refs/pull/864/head,refs/pull/865/head,refs/pull/865/merge,refs/pull/866/head,refs/pull/868/head,refs/pull/869/head,refs/pull/877/head,refs/pull/877/merge,refs/pull/878/head,refs/pull/879/head,refs/pull/881/head,refs/pull/886/head,refs/pull/886/merge,refs/pull/893/head,refs/pull/898/head,refs/pull/899/head,refs/pull/903/head,refs/pull/904/head,refs/pull/905/head,refs/pull/905/merge,refs/pull/906/head,refs/pull/907/head,refs/pull/907/merge,refs/pull/909/head,refs/pull/911/head,refs/pull/912/head,refs/pull/915/head,refs/pull/919/head,refs/pull/925/head,refs/pull/930/head,refs/pull/940/head,refs/pull/942/head,refs/pull/942/merge,refs/pull/947/head,refs/pull/948/head,refs/pull/951/head,refs/pull/952/head,refs/pull/954/head,refs/pull/958/head,refs/pull/96/head,refs/pull/96/merge,refs/pull/960/head,refs/pull/960/merge,refs/pull/962/head,refs/pull/968/head,refs/pull/973/head,refs/pull/98/head,refs/pull/98/merge,refs/pull/980/head,refs/pull/987/head,refs/pull/99/head,refs/pull/99/merge,refs/pull/995/head,refs/pull/998/head,refs/pull/998/merge,refs/tags/v0.0.1,refs/tags/v0.1.0,refs/tags/v0.1.1,refs/tags/v0.1.2,refs/tags/v0.1.3,refs/tags/v0.1.4,refs/tags/v0.1.5,refs/tags/v0.10.0,refs/tags/v0.10.1,refs/tags/v0.10.2,refs/tags/v0.10.3,refs/tags/v0.10.4,refs/tags/v0.2.0,refs/tags/v0.2.1,refs/tags/v0.2.10,refs/tags/v0.2.11,refs/tags/v0.2.12,refs/tags/v0.2.13,refs/tags/v0.2.14,refs/tags/v0.2.15,refs/tags/v0.2.16,refs/tags/v0.2.17,refs/tags/v0.2.18,refs/tags/v0.2.19,refs/tags/v0.2.2,refs/tags/v0.2.20,refs/tags/v0.2.21,refs/tags/v0.2.22,refs/tags/v0.2.3,refs/tags/v0.2.4,refs/tags/v0.2.5,refs/tags/v0.2.6,refs/tags/v0.2.7,refs/tags/v0.2.8,refs/tags/v0.2.9,refs/tags/v0.3.0,refs/tags/v0.3.1,refs/tags/v0.3.2,refs/tags/v0.3.3,refs/tags/v0.4.0,refs/tags/v0.4.1,refs/tags/v0.4.2,refs/tags/v0.4.3,refs/tags/v0.4.4,refs/tags/v0.4.5,refs/tags/v0.4.6,refs/tags/v0.4.7,refs/tags/v0.4.8,refs/tags/v0.4.9,refs/tags/v0.5.0,refs/tags/v0.5.1,refs/tags/v0.5.2,refs/tags/v0.5.3,refs/tags/v0.6.0,refs/tags/v0.7.0,refs/tags/v0.8.0,refs/tags/v0.8.1,refs/tags/v0.9.0,refs/tags/v0.9.1,refs/tags/v0.9.2,refs/tags/v0.9.3,refs/tags/v0.9.4,refs/tags/v0.9.5,refs/tags/v1.0.0,refs/tags/v1.1.0,refs/tags/v1.2.0,refs/tags/v1.2.1,refs/tags/v1.2.2,refs/tags/v1.3.0,refs/tags/v1.3.1,refs/tags/v1.3.2,refs/tags/v1.3.3,refs/tags/v2.0.0-rc.0,refs/tags/v2.0.0-rc.1,refs/tags/v2.0.0-rc.2,refs/tags/v2.0.0-rc.3,refs/tags/v2.0.0-rc.4,refs/tags/v2.0.0-rc.5,refs/tags/v2.0.0-rc.6,refs/tags/v2.0.0-rc.7,refs/tags/v2.0.0-rc.8,refs/tags/v2.0.0-rc.9,refs/tags/v2.1.0,refs/tags/v2.2.0,refs/tags/v2.3.0,refs/tags/v2.3.1,refs/tags/v3.0.0,refs/tags/v3.0.1,refs/tags/v3.0.2,refs/tags/v3.0.3,refs/tags/v3.0.4,refs/tags/v3.0.5,refs/tags/v3.0.6,refs/tags/v3.1.0,refs/tags/v3.2.0,refs/tags/v3.2.1,refs/tags/v4.0.0,refs/tags/v4.1.0,refs/tags/v4.2.1,refs/tags/v5.0.0,refs/tags/v5.0.1,refs/tags/v5.0.2,refs/tags/v5.0.3,refs/tags/v5.1.0,refs/tags/v6.0.0,refs/tags/v6.0.1,refs/tags/v6.0.2" for "https://github.com/cucumber/cucumber-js.git".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.

**Comment by DeepDiver1975** [comment]
refs #2175 - we need to upgrade cucumber ...

**Comment by DeepDiver1975** [comment]
Update to cucumber-js 6.0.2 has issues - let's postpone this.

@individual-it feel free to have a look - THX

https://drone.owncloud.services/daimler/daimler-design-system

**Comment by DeepDiver1975** [comment]
> could not find an easy way to fix `cucumber-pretty`

is there any upstream bug report on this? or is it only us facing this issue? THX

**Comment by individual-it** [comment]
cucumber-pretty is just not compatible with  cucumber-js 6.0, as the version number suggesting there have been API breaks. I will open a feature request

**Comment by individual-it** [comment]
cucumber-pretty has an update and put that in

**Comment by individual-it** [comment]
I reverted my previous changes and added those that still make sense to https://github.com/owncloud/phoenix/pull/2234

**Pull request merged**
