### PR TITLE
Bring back file versions

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
File version sidebar is back now ...

## How Has This Been Tested?
- :hand: 

## Screenshots (if appropriate):
Screenshot from 2019-04-10 16-28-35

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] move operation to store
- [ ] fix layout

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> When I restore file version the file doesn't appear until I refresh the page manually.

most likly related to way we bind the file list to the store elements .... or maybe we even do not properly update the store after restore ....

I'll look into this. THX for testing!

**Comment by LukasHirt** [comment]
> > When I restore file version the file doesn't appear until I refresh the page manually.
> 
> most likly related to way we bind the file list to the store elements .... or maybe we even do not properly update the store after restore ....
> 
> I'll look into this. THX for testing!

Sure, no problem 🙂

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2220/

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2221/

**Pull request merged**
