### PR TITLE
Personal settings

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Created basic account page where user can preview his username, display name, email and groups, logout button at account page and replaced button with oc-button in top-bar.

## How Has This Been Tested?

- test environment: Manually

### Desktop with all informations
image

### Desktop without email:
image

### Desktop with no group:
image

### Phone:
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary><p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary><p>





</p></details>

**Comment by DeepDiver1975** [comment]
Nice!

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary><p>





</p></details>

**Pull request merged**
