### PR TITLE
Added more babel plugins

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Added babel plugins for optional chaining and nullish coalescing operator and stopped importing core-js directly into the core.

### CODE REVIEW

**Comment by LukasHirt** [comment]
I guess here it doesn't make sense to include changelog item, does it?

**Comment by PVince81** [comment]
@LukasHirt if this strips down the release bundle I think it might be worth mentionning as it could decrease loading times and save mobile bandwidth :-)

**Comment by LukasHirt** [comment]
@PVince81 Changelog added.

**Comment by PVince81** [comment]
please fix conflict then merge :-)

**Pull request merged**
