### PR TITLE
Filter search term in open folder

### LINKED ISSUE #517: Filter files locally in the current loaded folder
# Scenario
```gherkin
Given a user has various files in a folder
When the user filters for <criteria>
Then only files/folders matching the <criteria> are displayed
 Examples:
    | criteria | 
    | mime-type is txt |
    | file is hidden |
    | file name contains 'abc' |
    | ... |
```

# Technical
- only client side operation
-- no server interaction

# UX
- we already have the filter button in th eupper right corner
- let's just reuse it

### PR DESCRIPTION
**Pull request by tempelgogo**
## Description
The second commit is the offline-search functionality for open folder.
To be able to reuse the SearchBar, i've designed some webpack alias magic to use inside app's build systems, visible in the first commit of this PR.

## Related Issue

- refs #172 
- close #517

## Motivation and Context
We need some way Interface in Phoenix which apps can use to import Models, Services, Mixins, etc...
One possible solution is to outsource them & publish them on npm, so we could import them in phoenix same as in apps. This may be an idea if our pattern library is available & grown, but we need some way to use them right now. To avoid proliferation of incorrect settings, i've created a little helper script located in phoenix root directory. Apps can wrap their webpack config up & it get's enriched with some nice path aliases.
I could adopt some more helper & mixin code if we got some interface for loading them in apps...

## Screenshots:
filenamefilter

## Types of changes

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] Code changes
- [X] Documentation ticket referenced

## Open tasks:

- [x] adopt UI. it's a filter function 
- [ ] talk about the new path aliases

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Nice start. THX
Searching in the currently folder (pure Client Side) is what i would Name "Filter". This is Something we need as Well but in a different context.

Search is What we consider a Server Side functionality and can search all Files of the User with the füll folder tree.

This is why the js-owncloud-client was extended with the search function.

**Comment by tempelgogo** [comment]
> Nice start. THX
> Searching in the currently folder (pure Client Side) is what i would Name "Filter". This is Something we need as Well but in a different context.
> 
> Search is What we consider a Server Side functionality and can search all Files of the User with the füll folder tree.
> 
> This is why the js-owncloud-client was extended with the search function.

@DeepDiver1975 I've seen your search method, thanks for implementing it. It's the following task, but we still have to discuss some things about that.

But the first part of issue #172 is named `filter files in current folder based on file name pattern`, so it belongs to this context in my opinion.
Besides that i would like to use a reuseable SearchBar for your new search method, so we can use the same look&feel in apps. I felt like the mechanism to load them was missing, so i've done this example to inject path aliases into files-app webpack. Files App is now able to load from 'oc_components/Spinner', for example.
The magic is visible in https://github.com/owncloud/phoenix/pull/513/commits/4487d870e0c085ed48435dc296c77418e3fe91e8
But this way, we abstract all path's under our control, and can change them in phoenix to influence the next app builds.

It wasn't the best idea to put the alias-loader into this "search for open folder" named PR, but could you take a look at it anyway, please :) ?
Is this workaround a possible solution to expose our components to apps ?

**Comment by DeepDiver1975** [comment]
> But the first part of issue #172 is named `filter files in current folder based on file name pattern`, so it belongs to this context in my opinion.

you are absolutly right - my fault - I should have taken more care here.
I'll split up the issue in two tickets.

**Comment by DeepDiver1975** [comment]
@tempelgogo my approach on registering components and make them usable in apps: https://github.com/owncloud/phoenix/commit/36146aee750c431de600fe5d0755099047fbe91d#diff-9e4fc1110432e662806df44bc5b846a5

**Pull request merged**
