### PR TITLE
remove less and sass loader

### LINKED ISSUE #540: Do we need sass?
As of today we install node-sass and sass-loader - see https://github.com/owncloud/phoenix/blob/00924b98d2f1dfe4e22aa85bedebaa623ff8158f/package.json#L53-L56

Installing node-sass is pulling a hell of dependencies into the docker image during build step:

https://github.com/owncloud/phoenix/blob/00924b98d2f1dfe4e22aa85bedebaa623ff8158f/Dockerfile#L4

Is sass needed anywhere? As far as I can tell: no
Do we need it in the future? No idea.

### PR DESCRIPTION
**Pull request by scramb**
## Description

Removed unused dependencies like less and sass from package.json & from webpack loader

## Related Issue

- Fixes #540

## How Has This Been Tested?

- :hand: 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Technical debt

## Checklist:

- [x] Code changes

### CODE REVIEW

**Comment by scramb** [comment]
I really can't find a dependency in the dockerfile which points to scss, sass or less. but there is no scss or sass in the code anymore. css-loader still loads vuetify stylesheets

**Comment by DeepDiver1975** [comment]
The dockerfile File adds Python and make and GCC ..... All only for building sass.

**Comment by DeepDiver1975** [comment]
Have a look at the Ticket .... Here is the Link to the Line in dockerfile 
00924b98d2f1dfe4e22aa85bedebaa623ff8158f

**Comment by scramb** [comment]
now i get your point - i'll remove the line, but i got some general thinks to add to the dockerfile... I'll come back with an update alter this day

**Pull request merged**
