### PR TITLE
Adjusted width of sidebar and allowed scroll in it

### LINKED ISSUE #1344: Need to scroll when having multiple users in the "auto complete list"
### Steps to reproduce
1. have two users "user1" and "user2"
2. as a third user open the sharing dialogue and type "user"

### Expected behaviour
both users should be shown

### Actual behaviour
first user is shown, scroll bar appears, need to scroll down to see second user

bug-1

### PR DESCRIPTION
**Pull request by LukasHirt**
## Motivation
We already talked in channel that the width needs to be adjusted because of acls. I even think it was done but it's gone so here we go again.

## Related issue
Fixes #1344 

## How Has This Been Tested?

- test environment: Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3637/15

<p>















</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3637/24

<p>



















</p></details>

**Comment by DeepDiver1975** [comment]
Looks like this is failing on smaller screens - please have a look @LukasHirt

**Comment by LukasHirt** [comment]
> Looks like this is failing on smaller screens - please have a look @LukasHirt

Should be fixed now. Let's see if it goes green 🤞

**Comment by LukasHirt** [comment]
@DeepDiver1975 green now

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3646/25

<p>















</p></details>

**Comment by DeepDiver1975** [comment]
conflict resolved ...

**Pull request merged**
