### PR TITLE
Update ODS to fix labels

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Update ODS to revision 1059.
Added search bar labels as required.
Fix buttonHidden value to be a real boolean.
Fix null label in rename dialog, as only string is allowed for the
label.

## Related Issue
None

## How Has This Been Tested?
Open web browser on files app:
- before the fix: lots of warnings about label
- after the fix: no more such warnings (except for virtual scroll, raised separately #2726)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by PVince81** [comment]
Test failure tests/acceptance/features/webUISharingInternalGroups/shareWithGroupsEdgeCases.feature:101


related to https://github.com/owncloud/owncloud-design-system/pull/557/

and now for some reason clicking an item in the autocomplete doesn't close the dropdown in the collaborators view

however the closing works in the design system, so maybe we missed an attribute or something...

**Comment by PVince81** [comment]
- [ ] ODS bug with oc-autocomplete and fillOnSelection https://github.com/owncloud/owncloud-design-system/issues/588

**Comment by PVince81** [comment]
some weird connection errors, even after restarting the build:
```
FetchError: request to http://localhost:8080/ocs/v2.php/apps/testing/api/v1/occ?format=json failed, reason: connect ECONNREFUSED 127.0.0.1:8080
```

wonder if it's related to changes in core maybe ?

@individual-it

**Comment by individual-it** [comment]
that thing should not connect to localhost:8080 but to http://phoenix

**Comment by individual-it** [comment]
that thing should not connect to localhost:8080 but to http://phoenix
the .drone.yml in that branch does not have the
```
SERVER_HOST: http://phoenix
```
settings, maybe a rebase on master will fix it

**Comment by PVince81** [comment]
rebased

**Pull request merged**
