### PR TITLE
Display indirect shares for links

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Display indirect link shares in the links panel when link shares exist on any parent resource.

## Related Issue
Fixes https://github.com/owncloud/phoenix/issues/2897
- [x] REQUIRES: indirect shares in collaborators: https://github.com/owncloud/phoenix/pull/2929
- [x] REQUIRES: link panel styling improvements: https://github.com/owncloud/phoenix/pull/2917
(the PR is based on top of the two PRs)

## How Has This Been Tested?
- manual test web UI
- [x] acceptance tests

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] fix styling, especially the "via" part
- [ ] tests
- [ ] changelog

### CODE REVIEW

**Comment by PVince81** [comment]
The feature works now and the tests pass.

However the styling isn't looking good, we have the "via" link alignment problem here as well.
Maybe this needs to be moved into a table as well like we did for collaborators.

@kulmann

**Comment by PVince81** [comment]
@kulmann apart from the styling I think the PR would be ready, CI has passed last time and I've just rebased.

Please review the current code. If you have time, can you take care of adjusting the styling like you did for collaborators, maybe with the table ?

**Comment by kulmann** [comment]
Bildschirmfoto 2020-01-30 um 12 46 01

**Comment by PVince81** [comment]
@kulmann seems you missed the mixin: https://github.com/owncloud/phoenix/pull/2932/commits/4b0340d8bc77ede5a7eac4e9c0157c76492045be

**Comment by PVince81** [comment]
last commits from @kulmann are ok :+1:

**Pull request merged**
