### PR TITLE
Block more then one click when deleting

### LINKED ISSUE #1537: Multiple files delete confirmation - can be confirmed multiple times
### Steps to reproduce
1. select multiple files
2. delete them all
3. click OK on the confirmation dialog
4. see deletions happening
5. click OK again
6. all deletions will be triggered again

### Expected behaviour
- button shall be grayed out
- or what ever

### Actual behaviour
- the user can click the button over and over again

### PR DESCRIPTION
**Pull request by Julian1998**
## Description
Added boolean hepler to detect clicks

## Related Issue

- Fixes #1537 

## How Has This Been Tested?

- try to force the confirm button to send an other delete request when in the dialog prompt

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4608/

<p>


















</p></details>

**Comment by DeepDiver1975** [comment]
Oh - damn ...

@Julian1998 I merged this too early ... see the acceptance screenshots - there is something broken :see_no_evil:

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUITrashbin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4608/

<p>












































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4608/

<p>



































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4608/

<p>























</p></details>

**Comment by Julian1998** [comment]
> Oh - damn ...
> 
> @Julian1998 I merged this too early ... see the acceptance screenshots - there is something broken

Oh damn. Yeah will have a look

**Pull request merged**
