### PR TITLE
Added params to the end of the list

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Added number of results, used space, last modification and total size to the bottom of the list.

## Motivation and Context
Users now have more available informations.

## How Has This Been Tested?

- test environment: Manually

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Create a proper implementation for smaller screens

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Screenshot from 2019-07-29 16-13-46

of 100% is not reasonable - the upper value will always be 100%.

We either show 5MB of 6GB or only the percentage ....

... but there is more to this ...

see https://github.com/owncloud/enterprise/issues/3393#issuecomment-509576384 and https://github.com/owncloud/enterprise/issues/3393#issuecomment-509576741

**Comment by DeepDiver1975** [comment]
- [ ] furthermore - we might want to keep this as a sticky footer. think about a long file list - the user has to scroll down to the end to see the total amount of files and folders ...
- [ ] and number of files and folder would be nicer instead of '26 results'

**Comment by LukasHirt** [comment]
> We either show 5MB of 6GB or only the percentage ....

Done

> furthermore - we might want to keep this as a sticky footer

Done

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUILogin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4686/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4685/

<p>
























</p></details>

**Pull request merged**
