### PR TITLE
Replace join-path usages with the path library

### PR DESCRIPTION
**Pull request by PVince81**
#  Description
Since we now include the "path" library, we don't need the "join-path"
library which only provides a subset of its features.

## Related Issue
Fixes https://github.com/owncloud/phoenix/issues/2922

## How Has This Been Tested?
- Manual test of relevant code pieces

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by LukasHirt** [comment]
Looking at the tests error it seems it might be still somewhere imported?

**Comment by PVince81** [comment]
oh, so it seems we used this lib in some tests as well. I'll recheck...

**Comment by PVince81** [comment]
it looks like join-path doesn't behave exactly like `path.join` when dealing with URLs, so I can't replace it in the tests as a lot of test code has such assumption in place.

I'll keep the join-paths dependency for now for tests

**Comment by PVince81** [comment]
pushed. let's see...

**Comment by PVince81** [comment]
@LukasHirt it went through this time

**Comment by LukasHirt** [comment]
I guess we don't need changelog item for this, right?

**Pull request merged**
