### PR TITLE
Retry clicking on delete confirmation popup

### PR DESCRIPTION
**Pull request by skshetry**
## Description

This PR handles retrying to click the popup dialog which has been failing quite a lot. 

## Related Issue

- Workaround for #1728. Requires further investigation. 

## How Has This Been Tested?

- locally, and CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by HariBhandari07** [comment]
LGTM

**Comment by skshetry** [comment]
Drone is broken. :(

**Comment by phil-davis** [comment]
Drone is back. I restarted the job.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6314/

<p>




</p></details>

**Comment by phil-davis** [comment]
Restarted drone again

**Comment by skshetry** [comment]
This won't pass without merging #2425.

**Comment by phil-davis** [comment]
I rebased this PR, and chery-picked the fix from #2425 
Hopefully CI will pass with both of these together.

**Pull request merged**
