### PR TITLE
Added oc-drop component

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Removed old oc-menu component and replaced it with oc-drop. In filter menu is this component replaced in PR #1000 

## How Has This Been Tested?

- test environment: Manually

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I think you need to upgrade ODS to 1.0.0-537 - otherwise oc-drop is not available

**Comment by LukasHirt** [comment]
> I think you need to upgrade ODS to 1.0.0-537 - otherwise oc-drop is not available

Right - I always forget to commit also yarn.lock 🤦‍♂️

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2471/

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2472/

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2474/

**Comment by ownclouders** [comment]
Find screenshots at https://minio.owncloud.com/phoenix/screenshots/2476/

**Comment by LukasHirt** [comment]
Cherrypicked and merged in #1000

**Pull request closed without merging**
