### PR TITLE
Remove duplicate 'has created folder' step definition

### PR DESCRIPTION
**Pull request by phil-davis**
That got merged accidentally today.

### CODE REVIEW

**Comment by phil-davis** [comment]
lint complained - I removed the import at line 6.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6323/

<p>




























</p></details>

**Comment by phil-davis** [comment]
Sadly the delete file/folder dialog box testing issue happened: https://drone.owncloud.com/owncloud/phoenix/6323/15/14
We were hoping that might be fixed.
Restarting drone...

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6324/

<p>

































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6328/

<p>






































</p></details>

**Comment by phil-davis** [comment]
This has been cherry-picked into PR #2417 because that PR fixes intermittent CI problems. So both together might pass more reliably.

**Comment by phil-davis** [comment]
Fixed in #2417

**Pull request closed without merging**
