### PR TITLE
remove leading slash from filenames

### LINKED ISSUE #3571: Trashbin file listing shows leading slashes
### Steps to reproduce
1. Delete a file
2. Go to the trashbin view

### Expected behaviour
Tell us what should happen
File listing should look like in the 'All Files' view.

### Actual behaviour
Tell us what happens instead
Filenames have a leading slash ('/')
Trashbin file listing

### Server configuration
I used the current ocis/master branch

### PR DESCRIPTION
**Pull request by C0rby**
## Description

Removed the leading slash from the filename in the trashbin view.

## Related Issue

- Fixes #3571 

## How Has This Been Tested?

- test environment: locally with ocis backend from ocis/master
- test case 1: Deleted a file and navigated to the trashbin view

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by C0rby** [comment]
Can I run the tests locally?
If yes, how?

**Comment by LukasHirt** [comment]
> Can I run the tests locally?

https://owncloud.github.io/clients/web/testing

**Comment by C0rby** [comment]
@LukasHirt. @individual-it, can you help me fix the acceptance test?

I can't quite figure out what I have to do... Or why it fails.
I understand that the failure is about listing the file after restoring but how is that related to my change?
```
Failures:

 1) Scenario: Restore a file from trashbin whose parent folder is renamed (attempt 2) # tests/acceptance/features/webUITrashbin/trashbinRestore.feature:102
 ✔ Before # tests/acceptance/setup.js:28
 ✔ Before # tests/acceptance/setup.js:32
 ✔ Before # tests/acceptance/setup.js:36
 ✔ Before # tests/acceptance/setup.js:46
 ✔ Before # tests/acceptance/setup.js:68
 ✔ Before # tests/acceptance/setup.js:75
 ✔ Before # tests/acceptance/stepDefinitions/filesContext.js:16
 ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:191
 ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:230
 ✔ Given user "user1" has been created with default attributes # tests/acceptance/stepDefinitions/provisioningContext.js:126
 ✔ And user "user1" has logged in using the webUI # tests/acceptance/stepDefinitions/loginContext.js:63
 ✔ And the user has browsed to the files page # tests/acceptance/stepDefinitions/filesContext.js:80
 ✔ Given the user has created file "simple-folder/file-to-delete-and-restore" # tests/acceptance/stepDefinitions/filesContext.js:807
 ✔ And the following files have been deleted by user "user1" # tests/acceptance/stepDefinitions/filesContext.js:201
 | name                                     |
 | simple-folder/file-to-delete-and-restore |
 ✔ And user "user1" has renamed folder "simple-folder" to "simple-folder-renamed" # tests/acceptance/stepDefinitions/filesContext.js:778
 ✔ When the user browses to the trashbin page # tests/acceptance/stepDefinitions/filesContext.js:60
 ✖ And the user restores file "simple-folder/file-to-delete-and-restore" from the trashbin using the webUI # tests/acceptance/stepDefinitions/filesContext.js:742
 Timed out while waiting for element <//span[@class="oc-file-name"][text()='simple-folder/file-to-delete-and-restore' and not(../span[@class="oc-file-extension"])]/../../../../../div[@data-is-visible="true"]> to be present for 20000 milliseconds. - expected "visible" but got: "not found" (20016ms)
 at Proxy.waitForFileWithPathVisible (/var/www/owncloud/phoenix/tests/acceptance/pageObjects/FilesPageElement/filesList.js:316:10)
 at Proxy._callee7$ (/var/www/owncloud/phoenix/tests/acceptance/pageObjects/FilesPageElement/filesList.js:89:18)
 at new Promise (<anonymous>)
 at Proxy.restoreFile (/var/www/owncloud/phoenix/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:16)
 at World.<anonymous> (/var/www/owncloud/phoenix/tests/acceptance/stepDefinitions/filesContext.js:746:51)
 - Then the error message with header "Restoration of file-to-delete-and-restore failed" should be displayed on the webUI # tests/acceptance/stepDefinitions/generalContext.js:43
 - And as "user1" the file with original path "simple-folder/file-to-delete-and-restore" should exist in the trashbin # tests/acceptance/stepDefinitions/webdavContext.js:143
 - And as "user1" file "simple-folder-renamed/file-to-delete-and-restore" should not exist # tests/acceptance/stepDefinitions/webdavContext.js:35
 - And as "user1" file "simple-folder/file-to-delete-and-restore" should not exist # tests/acceptance/stepDefinitions/webdavContext.js:35
 ✔ After # tests/acceptance/stepDefinitions/provisioningContext.js:200
 ✔ After # tests/acceptance/stepDefinitions/generalContext.js:235
 ✔ After # tests/acceptance/stepDefinitions/generalContext.js:215
 ✔ After # tests/acceptance/setup.js:110
 ✔ After # tests/acceptance/setup.js:106
 ✔ After # tests/acceptance/setup.js:102
 ✔ After # tests/acceptance/setup.js:95
 ✔ After # tests/acceptance/setup.js:86
 ✔ After # tests/acceptance/setup.js:54
```

**Comment by individual-it** [comment]
@C0rby It cannot find the file to restore, how did your commit change the DOM if a file is deleted from a sub-folder?

**Comment by individual-it** [comment]
look at that. I've deleted the file `efg.txt` from the folder `abcd`
but in the trash the folder-name is `bcd` only

image

**Comment by C0rby** [comment]
> look at that. I've deleted the file `efg.txt` from the folder `abcd`
> but in the trash the folder-name is `bcd` only
> 
> image

Did you test it with the oc10 backend?
If so then that means I can close this pr and the issue and we have to fix it in ocis...

**Comment by individual-it** [comment]
@C0rby yes I've tested oc10 only

**Comment by C0rby** [comment]
Ok thanks.

Closing this pr because the response from ocis is incorrect.

**Pull request closed without merging**
