### PR TITLE
Adjusted browserslist to exclude IE 11

### PR DESCRIPTION
**Pull request by LukasHirt**
## Related Issue

- Refs #2967

## How Has This Been Tested?

- test environment: Manually
1. Try and build Phoenix

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by LukasHirt** [comment]
Leaving out changelog item since this seems too much technical and we already have one about not supporting IE 11.

**Comment by kulmann** [comment]
> Leaving out changelog item since this seems too much technical and we already have one about not supporting IE 11.

@LukasHirt for future situations, you could add the link of the PR to the respective changelog item, just for the sake of completeness. Won't create a new PR just for this now. 😅

**Comment by LukasHirt** [comment]
> you could add the link of the PR to the respective changelog item

Then we'd be messing up items with different versions.

**Comment by kulmann** [comment]
> > you could add the link of the PR to the respective changelog item
> 
> @kulmann Then we'd be messing up items with different versions.

@LukasHirt yeah, ignore my comment. Thought it was still unreleased. But of course, if it's already release then we can't add to it anymore.

**Pull request merged**
