### PR TITLE
Feature/open sidebar on row select

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
The sidebar is no longer driven by the checked file(s).
Row selection is now triggering the side bar

## Related Issue
- [x] requires https://github.com/owncloud/phoenix/pull/1493
- [ ] requires https://github.com/owncloud/owncloud-design-system/pull/416

## How Has This Been Tested?
- :hand: 

## Screenshots
Screenshot from 2019-07-10 15-37-29
Screenshot from 2019-07-10 15-37-11

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3989/12

<p>

























</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3989/13

<p>

























</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3991/12

<p>

























</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3991/13

<p>

























</p></details>

**Comment by DeepDiver1975** [comment]
tests are failing because of the clicks done by the web driver are triggering the sidebar .... need to have a closer look .....

**Comment by DeepDiver1975** [comment]
it's the click on the dialog buttons ....

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3992/12

<p>

























</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/3992/13

<p>



























</p></details>

**Pull request merged**
