### PR TITLE
retry failing acceptance tests

### PR DESCRIPTION
**Pull request by individual-it**
## Description
retry tests that are failing
currently using directly the branch with the fix, waiting for it to be merged https://github.com/cucumber/cucumber-js/pull/1205

## Motivation and Context
make CI more stable

## Screenshots (if appropriate):
that how it looks when it failed also the second time
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by individual-it** [comment]
should we merge this PR or wait till the PR to cucumber-js is merged and a new version is build?

**Comment by DeepDiver1975** [comment]
Looks like upstream is interested in getting this merged - at least someone reviewed the PR a few hours ago.

**Comment by DeepDiver1975** [comment]
Let wait a few more days.

**Comment by individual-it** [comment]
> Looks like upstream is interested in getting this merged - at least someone reviewed the PR a few hours ago.

Yes I will try to implement the change requests today

**Pull request merged**
