### PR TITLE
Implement the file filter

### PR DESCRIPTION
**Pull request by OshanIvantha**
This PR implements filtering of the files and directories. 

screen shot 2018-10-01 at 2 30 21 am

**TODO :** Filtering of the hidden files is not a part of this PR as the hidden file feature is not yet added to Phoenix.

### CODE REVIEW

**Comment by felixheidecke** [comment]
The "hidden files" was something I put in to make the list longer for the dummy :-P
Never thought about if it makes any sense.

**Comment by DeepDiver1975** [comment]
> The "hidden files" was something I put in to make the list longer for the dummy :-P
> Never thought about if it makes any sense.

I though you had a look at owncloud and got the requirement from the existing user interface

screenshot from 2018-10-01 11-44-23

**Comment by felixheidecke** [comment]
For the record: Almost everything I did in Phoenix (UI wise) was made up on the spot for click dummy purposes … nothing is final ;-)

**Comment by DeepDiver1975** [comment]
@OshanIvantha please resolve conflict

**Comment by OshanIvantha** [comment]
> @OshanIvantha please resolve conflict

Done. I also added filtering of the files with the . character.

**Pull request merged**
