### PR TITLE
Moved sidebar navigation under top bar

### PR DESCRIPTION
**Pull request by LukasHirt**
## How Has This Been Tested?

- test environment: Manually

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by LukasHirt** [comment]
Styles improving padding and text-transform will come with the next release of ODS.

**Comment by PVince81** [comment]
can you rebase to get the ODS update ?

**Comment by PVince81** [comment]
@LukasHirt can you rebase and update the screenshot ?

**Comment by LukasHirt** [comment]
@PVince81 Sure, will do

**Comment by LukasHirt** [comment]
@PVince81 Rebased and updated screenshot

**Comment by PVince81** [comment]
screenshot still has capitalized entries ?

**Comment by PVince81** [comment]
Tested, looks fine

**Comment by LukasHirt** [comment]
Agh must have had some confusion in versions locally... Thanks a lot for testing!

**Pull request merged**
