### PR TITLE
PWA

### PR DESCRIPTION
**Pull request by OshanIvantha**
## M3 Adapt Phoenix to PWA:

- [x] M3.1 Wrap Phoenix into a shell-app following Google best practices
- [x] M3.2 Test PWA compatibility with Lighthouse
- [x] M3.3 Cache file metadata from ownCloud into the browser cache
- [x] M3.4 Detect when user goes offline and show warning banner
- [x] M3.5 Reconcile changes when network connection comes back
- [x] M3.6 Test offline metadata scenarios
---
- [x] Adapt to new file structure in PR #163

### CODE REVIEW

**Comment by OshanIvantha** [comment]
References #192

**Comment by OshanIvantha** [comment]
@labkode Phoenix get a PWA score of 82% with this PR.
screen shot 2018-07-12 at 11 14 53 am

**Comment by OshanIvantha** [comment]
@labkode This PR at its current state gets a PWA score of 82% in lighthouse.
screen shot 2018-07-12 at 11 14 53 am

**Comment by OshanIvantha** [comment]
@felixheidecke I rebased. Please take a look. 
Btw running `npm run lint' didn't give me any linting issues. 

Thanks

**Comment by DeepDiver1975** [comment]
@felixheidecke merge?

**Pull request merged**
