### PR TITLE
Run failing trashbin tests multiple times

### PR DESCRIPTION
**Pull request by HariBhandari07**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by HariBhandari07** [comment]
@individual-it have a look

**Comment by individual-it** [comment]
looks good, please link from the original PR

**Comment by HariBhandari07** [comment]
@individual-it done

**Comment by individual-it** [comment]
I think we can close this, as this was only a testing PR

**Pull request closed without merging**
