### PR TITLE
Prepare release 0.10.0

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Comment by PVince81** [comment]
failures :-(

```

1) Scenario: Create a folder with default name (attempt 2) # tests/acceptance/features/webUICreateFilesFolders/createFolders.feature:21
--
```

**Comment by PVince81** [comment]
@individual-it @dpakach ^

**Comment by LukasHirt** [comment]
@PVince81 Let's restart it? Seems like it might be a random failure since the other job passed 🤷

**Comment by PVince81** [comment]
I've restarted it now.

**Comment by dpakach** [comment]
> failures :-(
> 
> ```
> 
> 1) Scenario: Create a folder with default name (attempt 2) # tests/acceptance/features/webUICreateFilesFolders/createFolders.feature:21
> --
> ```

Yeah seems to be a flaky test. Will need further investigation to see what's causing it.
created a issue for that https://github.com/owncloud/phoenix/issues/3500

**Pull request merged**
