### PR TITLE
Upgrade all libs

### PR DESCRIPTION
**Pull request by PVince81**
As usual...

### CODE REVIEW

**Comment by PVince81** [comment]
did I update too hard ?

```
+ yarn run acceptance-tests-drone
yarn run v1.19.1
warning package.json: "dependencies" has dependency "deepmerge" with range "^4.0.0" that collides with a dependency in "devDependencies" of the same name with version "^4.2.1"
$ cucumber-js --retry 1 --require-module @babel/register --require-module @babel/polyfill --require tests/acceptance/setup-drone.js --require tests/acceptance/stepDefinitions --format node_modules/cucumber-pretty tests/acceptance/features/$TEST_CONTEXT -t "${TEST_TAGS}"
Error: Cannot find module 'nightwatch/lib/api/protocol'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/owncloud/phoenix/node_modules/nightwatch-api/lib/client.js:16:40)
    at Module._compile (module.js:653:30)
    at Module._compile (/var/www/owncloud/phoenix/node_modules/cucumber/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (/var/www/owncloud/phoenix/node_modules/cucumber/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/owncloud/phoenix/node_modules/nightwatch-api/lib/index.js:13:38)
    at Module._compile (module.js:653:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

some nightwatch issue ? should we lock the versions ? @individual-it

**Comment by individual-it** [comment]
`nightwatch-api` did not got updated to the correct version, tried that but now we get 
`error nightwatch-api@3.0.1: The engine "node" is incompatible with this module. Expected version ">= 10.0.0". Got "8.16.2"`

**Comment by individual-it** [comment]
trying with new node version, after https://github.com/owncloud-ci/php/pull/110 is merged the last commit in this PR can be reverted

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>PrivateLinks</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6827/

<p>





</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>iPhone</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6827/

<p>







</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingAutocompletion</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6827/

<p>






</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>XGAPortrait</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6827/

<p>







</p></details>

**Comment by HariBhandari07** [comment]
@PVince81 can you make an update of all libs except nightwatch and nightwatch api. In the updated versions of nightwatch it gets stuck after callback return. I have created an issue here: https://github.com/mucsi96/nightwatch-api/issues/824

**Comment by individual-it** [comment]
@HariBhandari07 pin the versions of nightwatch and nichtwatch-api in the json file to the old versions that are known to work

**Comment by HariBhandari07** [comment]
```  
  "nightwatch": "^1.2.2",
  "nightwatch-api": "^2.3.0",
```
works fine

**Comment by PVince81** [comment]
@HariBhandari07 please push the sticky versions (package.json + yarn.lock) and hopefully CI will pass now

**Comment by PVince81** [comment]
Cool, it worked!

@individual-it can you revert the temp docker image if that makes sense ?

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>SharingAcceptShares</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/6913/

<p>






</p></details>

**Comment by individual-it** [comment]
@PVince81 CI seems to be happy now

**Comment by skshetry** [comment]
The CI was failing due to a regression in https://github.com/nightwatchjs/nightwatch/issues/2262. This has been fixed in `v1.3.2`, but, still https://github.com/mucsi96/nightwatch-api/issues/824 can be a problem.

**Comment by individual-it** [comment]
nightwatch is currently locked to "1.2.4"

**Pull request merged**
